select * from customer limit 20
-- Q.1) what is the total revenue generated by male vs female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender


-- Q.2) which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (Select AVG(purchase_amount) from customer)

-- Q.3) Which are the top 5 product with the highest avg review rating?
select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q. 4) Compare the avg purchase amount btw. standard and express shipping?
select shipping_type,
ROUND(AVG(purchase_amount),2)
from customer
WHERE shipping_type IN ('Standard', 'Express')
group by shipping_type


-- Q. 5) Do subscribed customer spend more? compare avg spend and total revenue btw. subscriber and non-subscriber?
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;


-- Q. 6) Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
ROUND(100*SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;



-- Q. 7) Segment customers into new, returning, and loyal based on their total no. of previous purchases, and
--       show the count of each segment?
with customer_type as (
select customer_id, previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
from customer
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment

-- Q. 8) WHat are the top 3 most purchased products within each category?
with item_counts as (
select category, 
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3
--why here used row number instead of rank dense rank becauseFor your query, ROW_NUMBER() is appropriate 
--if your requirement is "return exactly the top 3 items in each category." If the requirement is 
--"include all items tied in the top 3 positions," then RANK() or DENSE_RANK() would be a better choice.

--Q. 9) Are  customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

-- Q. 10)  What is the revenue contribution og each age group?
select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;